name: Backend Tests

on:
  push:
    branches:
      - dev_backend  # Adjust the branch name as needed

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install  # You may use yarn if preferred
      working-directory: backend

    - name: Run tests
      run: npm test  # Adjust the test command based on your setup
      working-directory: backend
