name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (frontend)
        uses: actions/setup-node@v2
        with:
          node-version: 14
        working-directory: frontend/chrono-quest

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend/chrono-quest

      - name: Build frontend
        run: npm run build
        working-directory: frontend/chrono-quest
