name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend/chrono-quest

    - name: Install backend dependencies
      run: npm install
      working-directory: backend

    - name: Build frontend
      run: npm run build
      working-directory: frontend/chrono-quest
      
    - name: Move build artifacts to main branch
      if: success()
      run: |
        mkdir -p ${{ runner.workspace }}/build
        mv frontend/chrono-quest/build/* ${{ runner.workspace }}/build/
        git config --global user.email "hengquan0204@gmail.com"
        git config --global user.name "keeganchua"
        git add -A
        git commit -m "Add build artifacts"
        git push
