name: Frontend Tests

on:
  pull_request:
    branches:
      - dev_frontend

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: frontend/chrono-quest

      - name: Run frontend tests
        run: npm test
        working-directory: frontend/chrono-quest
