name: Integration Testing

on:
  push:
    branches:
      - dev_frontend

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev_frontend

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install
      working-directory: frontend/chrono-quest

    - name: Build frontend
      run: npm run build
      working-directory: frontend/chrono-quest

    - name: Pull backend code from dev_backend
      run: |
        git remote add backend https://github.com/keeganchua/chronoquest.git
        git fetch backend dev_backend
        git checkout dev_frontend
        git merge backend/dev_backend --no-commit --no-ff
        # Resolve any merge conflicts if necessary
        # Continue with the merge
        git commit -m "Merge changes from dev_backend for integration testing"
      working-directory: backend  

    - name: Start backend server
      run: npm start
      working-directory: backend

    - name: Wait for backend to start
      run: sleep 10 # Adjust the duration based on how long it takes for your backend to start

    - name: Run integration tests
      run: npm test:integration
      working-directory: frontend/chrono-quest
