name: Main Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  localhost-integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Install Dependencies and Start Frontend
        run: |
          cd frontend/chrono-quest
          npm install
          npm start &

      - name: Install Dependencies and Start Backend
        run: |
          cd backend
          npm install
          nohup npm start &    
          
      - name: Wait for Applications to Start
        run: |
          # Wait for a few seconds to allow the applications to start.
          sleep 10

      - name: Run Integration Tests
        run: |
          cd frontend/chrono-quest
          npm test:integration
