on:
  push:
    branches:
      - main

jobs:
  localhost-integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Install Dependencies and Start Frontend
        run: |
          cd frontend/chrono-quest
          npm install
          npm start &

      - name: Install Dependencies and Start Backend
        run: |
          cd backend
          npm install
          nohup npm start &    
          
      - name: Wait for Applications to Start
        run: |
          # Wait for a few seconds to allow the applications to start.
          sleep 10

      - name: Run Cypress Tests
        run: |
          cd frontend/chrono-quest
          npm run cy:run
        env:
          CYPRESS_baseUrl: 'http://localhost:3001'

      - name: Build Frontend React Application
        run: |
          cd frontend/chrono-quest
          npm run build
          
      - name: Deploy to GitHub Pages
        run: |
          cd frontend/chrono-quest
          npm install -g gh-pages
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
